CREATE TABLE `message` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `message_id` varchar(50) DEFAULT NULL COMMENT '消息在业务里的id',
  `data` text COMMENT '消息内容',
  `receiver` varchar(50) DEFAULT NULL COMMENT '接收者',
  `tunnel` varchar(30) DEFAULT NULL COMMENT '使用通道',
  `biz` varchar(30) DEFAULT NULL COMMENT '业务',
  `head` tinyint(1) DEFAULT NULL COMMENT '是否优先发送',
  `try_times` int(11) DEFAULT NULL COMMENT '尝试次数',
  `policy` varchar(255) DEFAULT NULL COMMENT '推送策略',
  `status` int(11) DEFAULT NULL COMMENT '推送状态',
  `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `receipt_time` timestamp NULL DEFAULT NULL COMMENT '收到回执时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_mrtb` (`message_id`,`receiver`,`tunnel`,`biz`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='消息推送的消息表';

CREATE TABLE `push_record` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `message_id` varchar(50) DEFAULT NULL COMMENT '消息唯一id',
  `receiver` varchar(50) DEFAULT NULL COMMENT '接收者',
  `tunnel` varchar(30) DEFAULT NULL COMMENT '使用通道',
  `biz` varchar(30) DEFAULT NULL COMMENT '业务',
  `push_order` bigint(20) DEFAULT NULL COMMENT '推送顺序',
  `stateful` tinyint(1) DEFAULT NULL COMMENT '是否有状态的',
  `duplex` tinyint(1) DEFAULT NULL COMMENT '是否双向',
  `ordered` tinyint(1) DEFAULT NULL COMMENT '是否有序',
  `timeout_mills` bigint(20) DEFAULT NULL COMMENT '回执超时时间',
  `trigger_time` timestamp NULL DEFAULT NULL COMMENT '计划推送时间',
  `retry_stateful` tinyint(1) DEFAULT NULL COMMENT '重试时是否有状态',
  `retry_duplex` tinyint(1) DEFAULT NULL COMMENT '重试时是否双向',
  `retry_ordered` tinyint(1) DEFAULT NULL COMMENT '重试时是否有序',
  `retry_timeout_mills` bigint(20) DEFAULT NULL COMMENT '重试时的回执超时时间',
  `retry` int(11) DEFAULT NULL COMMENT '重试次数',
  `follow_suggestion` tinyint(1) DEFAULT NULL COMMENT '是否采纳建议重试时间',
  `retry_trigger_time` timestamp NULL DEFAULT NULL COMMENT '重试的计划推送时间',
  `try_times` int(11) DEFAULT NULL COMMENT '已经尝试次数',
  `status` int(11) DEFAULT NULL COMMENT '状态',
  `cause` int(11) DEFAULT NULL COMMENT '失败原因',
  `tip` text COMMENT '失败描述',
  `suggest_time` timestamp NULL DEFAULT NULL COMMENT '建议重试时间',
  `create_time` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `push_time` timestamp NULL DEFAULT NULL COMMENT '推送开始时间',
  `finish_time` timestamp NULL DEFAULT NULL COMMENT '推送结束时间',
  PRIMARY KEY (`id`),
  KEY `idx_r_t_b` (`receiver`,`tunnel`,`biz`,`push_order`,`trigger_time`,`status`),
  KEY `idx_message` (`message_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='消息推送的推送记录表';
